apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    name: {{ .Values.appName }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          command:
            - sh
            - -c
            - java -jar /kafka-streams-explore/kafka-streams-explore.jar
          volumeMounts:
            - mountPath: /kafka-streams-explore/kafka-stream/state-stores
              name: persistent-store
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: persistent-store
          persistentVolumeClaim:
            claimName: kafka-streams-persistent

